### ISSUE TITLE
spenden2014.json holds a lot of data from 2013?

### ISSUE THREAD

**Issue by asmaier** [opendatacity/parteispenden-recherche#1]
The file
 https://github.com/opendatacity/parteispenden-recherche/blob/master/bin/data/spenden2014.json 
has a lot of entries saying "jahr": 2013. Is this an error? 
The file
https://raw.githubusercontent.com/opendatacity/parteispenden-recherche/master/web/assets/data/parteispenden.json
ends with data from 2013, although there is also some data from 2014 in between. 
I believe that either the sort ordering by year got messed up or that the last entries should in fact belong to year 2014, not 2013.

**Comment by marcomaas** [comment]
thanks - currently we are unable to maintain the data file - but pull
requests are more than welcome. next update is expected for february, we'll
plan to look at the data consistency then.
regards, marco

On Sun, Dec 13, 2015 at 7:59 PM, asmaier <notifications@github.com> wrote:

> The file
>
> https://githubcom/opendatacity/parteispenden-recherche/blob/master/bin/data/spenden2014json
> has a lot of entries saying "jahr": 2013 Is this an error?
> The file
>
> https://rawgithubusercontentcom/opendatacity/parteispenden-recherche/master/web/assets/data/parteispendenjson
> ends with data from 2013, although there is also some data from 2014 in
> between
> I believe that either the sort ordering by year got messed up or that the
> last entries should in fact belong to year 2014, not 2013
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opendatacity/parteispenden-recherche/issues/1>.
>



-- 
-- 
Diese Mail könnte verschlüsselt sein. Wenn Sie ein Interesse haben, dass
unsere Unterhaltung nicht mitgelesen wird, kann ich den künftigen
Mailverkehr verschlüsseln.


Marco Maas, Louise-Schröder-Str. 17, 22767 Hamburg, Tel. +49 163 6666 245
Datenfreunde GmbH i. G., Singerstr. 109, 10179 Berlin, Email:
mm@datenfreunde.com, Internet: www.opendatacity.de
USt-IdNr.: DE289682945, FA Berlin für Körperschaften II, Bankverbindung:
IBAN: DE80430609671149723500, SWIFT/BIC: GENODEM1GLS
www.opendatacity.de, www.datenfreunde.com, www.themaastrix.net,
www.twitter.com/themaastrix, www.venturemedia.de, www.viergleicheins.de
<http://www.viergleicheins.de/>

Nominierungen, Preise und Auszeichnungen:
http://www.themaastrix.net/preise-und-auszeichnungen/
